set number
set exrc
set relativenumber
set nohlsearch
set hidden 
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set clipboard+=unnamedplus
set expandtab
set smartindent
set bg=dark
" set nowrap
set noswapfile
set nobackup
set undodir=~/.cache/vim/undodir
set undofile
set incsearch
set scrolloff=3
set nocompatible
set signcolumn=yes
set guicursor=

set spell spelllang=en_gb

syntax enable






let mapleader = " "


function! Compile()
    execute "w %"
    execute "! pdflatex %"
endfunction

function! ShowPDF()
    execute "! zathura $(echo % \| sed 's/tex$/pdf/') & disown"
endfunction

nnoremap <leader>c :call Compile()<CR><CR>
nnoremap <leader>s :call ShowPDF()<CR><CR>
