set number
set exrc
set relativenumber
set nohlsearch
set hidden 
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set clipboard+=unnamedplus
set expandtab
set smartindent
set bg=dark
" set nowrap
set noswapfile
set nobackup
set undodir=~/.cache/vim/undodir
set undofile
set incsearch
set scrolloff=3
set nocompatible
set signcolumn=yes
set guicursor=

set spell spelllang=en_gb

syntax enable






let mapleader = " "


function! Compile()
    execute "w %"
    execute "! pdflatex %"
endfunction


nnoremap <leader>c :call Compile()<CR><CR>

" FAIL
" nnoremap <leader>c :! pdflatex % <CR><CR>
" nnoremap <leader>s :! zathura $(echo % \| sed 's/tex$/pdf/')
" nnoremap <leader>s :! zathura %<.pdf<CR><CR>
" nnoremap <leader>s :! zathura <c-r>%<.pdf<CR><CR>
