set number
set exrc
set relativenumber
set nohlsearch
set hidden 
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set bg=dark
set nowrap
set noswapfile
set nobackup
set undodir=~/.cache/vim/undodir
set undofile
set incsearch
set scrolloff=8
set signcolumn=yes
set guicursor=

let mapleader = " "

if !has('nvim')
    set viminfo+=n~/.cache/vim/viminfo
endif
